/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Clases.Ciudad;
import Clases.Comuna;
import Clases.Region;
import Metodos.CRUD;
import Metodos.Formato;
import Metodos.Validar;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class registrarCliente extends javax.swing.JFrame {

    CRUD c = new CRUD();
    Formato f = new Formato();
    Validar v = new Validar();
    modificarCliente mc = new modificarCliente();

    /**
     * Creates new form registrarCliente
     */
    public registrarCliente() {
        initComponents();

        c.mostrar_c(Tabla_c);

        DefaultComboBoxModel rg = new DefaultComboBoxModel(c.mostrarRegion());
        jcbxRegion.setModel(rg);

    }

    public void Limpiar() {
        jtfCampo.setText("");
        jtfRut_c.setText("");
        jtfRut2_c.setText("");
        jtfNombre_c.setText("");
        jtfApp_c.setText("");
        jtfApm_c.setText("");
        jtfDireccion_c.setText("");
        jtfCorreo_c.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfDireccion_c = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btxEliminar_Cliente = new javax.swing.JButton();
        jtfApp_c = new javax.swing.JTextField();
        btxModificar_Cliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_c = new javax.swing.JTable();
        jtfNombre_c = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnFiltro = new javax.swing.JButton();
        jtfCampo = new javax.swing.JTextField();
        jtfRut2_c = new javax.swing.JTextField();
        jcbxTipoFiltro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtCancelar = new javax.swing.JButton();
        jtfRut_c = new javax.swing.JTextField();
        jbtLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCorreo_c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfApm_c = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jcbxRegion = new javax.swing.JComboBox<>();
        jcbxCiudad = new javax.swing.JComboBox<>();
        jcbxComuna = new javax.swing.JComboBox<>();
        btxActualizar_Cliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jbtAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Clientes");

        jLabel11.setText("Region:");

        jLabel10.setText("Comuna:");

        jLabel9.setText("Ciudad:");

        jtfDireccion_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDireccion_cActionPerformed(evt);
            }
        });

        jLabel7.setText("Dirección:");

        btxEliminar_Cliente.setText("Eliminar");
        btxEliminar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxEliminar_ClienteActionPerformed(evt);
            }
        });

        btxModificar_Cliente.setText("Modificar");
        btxModificar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxModificar_ClienteActionPerformed(evt);
            }
        });

        Tabla_c.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Rut", "Nombre", "Direccion", "Comuna", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_cMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_c);

        jLabel4.setText("Nombre:");

        jbtnFiltro.setText("Filtrar");
        jbtnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiltroActionPerformed(evt);
            }
        });

        jtfCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCampoActionPerformed(evt);
            }
        });

        jtfRut2_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRut2_cActionPerformed(evt);
            }
        });

        jcbxTipoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Rut", "Nombre" }));
        jcbxTipoFiltro.setToolTipText("");
        jcbxTipoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxTipoFiltroActionPerformed(evt);
            }
        });

        jLabel1.setText("-");

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtLimpiar.setText("Limpiar");
        jbtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Rut:");

        jbtRegistrar.setText("Registrar");
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellido Paterno:");

        jLabel3.setText("Correo Electronico:");

        jtfCorreo_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCorreo_cActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido Materno:");

        jcbxRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbxRegionItemStateChanged(evt);
            }
        });

        jcbxCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbxCiudadItemStateChanged(evt);
            }
        });
        jcbxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCiudadActionPerformed(evt);
            }
        });

        btxActualizar_Cliente.setText("Actualizar");
        btxActualizar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxActualizar_ClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefono:");

        jbtAgregar.setText("Agregar");
        jbtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jbtRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jbtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfRut_c, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfRut2_c, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfNombre_c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfApp_c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCorreo_c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfDireccion_c, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jtfApm_c)))))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcbxTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btxModificar_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btxActualizar_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btxEliminar_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtAgregar)
                    .addComponent(jcbxRegion, 0, 298, Short.MAX_VALUE)
                    .addComponent(jcbxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbxComuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnFiltro))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btxActualizar_Cliente)
                    .addComponent(btxModificar_Cliente)
                    .addComponent(btxEliminar_Cliente))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfRut_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtfRut2_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jcbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jcbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApp_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jcbxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfApm_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jbtAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfDireccion_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCorreo_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLimpiar)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtRegistrar))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDireccion_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDireccion_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDireccion_cActionPerformed

    private void jtfRut2_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRut2_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRut2_cActionPerformed

    private void jcbxTipoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxTipoFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxTipoFiltroActionPerformed

    private void jbtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpiarActionPerformed

        Limpiar();

    }//GEN-LAST:event_jbtLimpiarActionPerformed

    private void jtfCorreo_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorreo_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorreo_cActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed

        this.dispose();

    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgregarActionPerformed

        registrarNumeroC rg = new registrarNumeroC();
        rg.setVisible(true);
        rg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jbtAgregarActionPerformed

    private void jcbxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCiudadActionPerformed


    }//GEN-LAST:event_jcbxCiudadActionPerformed

    private void jcbxRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbxRegionItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Region reg = (Region) jcbxRegion.getSelectedItem();

            DefaultComboBoxModel cd = new DefaultComboBoxModel(c.mostrarCiudad(reg.getId_region()));
            jcbxCiudad.setModel(cd);
            jcbxComuna.removeAllItems();
        }


    }//GEN-LAST:event_jcbxRegionItemStateChanged

    private void jcbxCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbxCiudadItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            Ciudad ciud = (Ciudad) jcbxCiudad.getSelectedItem();

            DefaultComboBoxModel comuna = new DefaultComboBoxModel(c.mostrarComuna(ciud.getId_ciudad()));
            jcbxComuna.setModel(comuna);
        }

    }//GEN-LAST:event_jcbxCiudadItemStateChanged

    private void btxActualizar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxActualizar_ClienteActionPerformed

        c.mostrar_c(Tabla_c);

    }//GEN-LAST:event_btxActualizar_ClienteActionPerformed

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed

        if (v.valCliente(jtfRut_c, jtfRut2_c, jtfNombre_c, jtfApp_c, jtfApm_c, jtfDireccion_c, jtfCorreo_c, (Comuna) jcbxComuna.getSelectedItem())) {
            c.guardar_c((Comuna) jcbxComuna.getSelectedItem(), f.formatoRut(jtfRut_c, jtfRut2_c), f.formatoNombre(jtfNombre_c), f.formatoNombre(jtfApp_c), f.formatoNombre(jtfApm_c), f.formatoNombre(jtfDireccion_c), f.formatoNombreCorreo(jtfCorreo_c));
        }

    }//GEN-LAST:event_jbtRegistrarActionPerformed

    private void btxModificar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxModificar_ClienteActionPerformed

        mc.Limpiar();
        mc.setVisible(true);
        mc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);


    }//GEN-LAST:event_btxModificar_ClienteActionPerformed

    private void btxEliminar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxEliminar_ClienteActionPerformed

        if (Tabla_c.getSelectedRow() >= 0) {
            int des = JOptionPane.showConfirmDialog(null, "Eliminar Cliente", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (des == JOptionPane.YES_OPTION) {

                c.eliminar_c(Tabla_c);
                JOptionPane.showMessageDialog(null, "Cliente eliminado con exito");
                c.mostrar_c(Tabla_c);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un campo");
        }


    }//GEN-LAST:event_btxEliminar_ClienteActionPerformed

    private void Tabla_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_cMouseClicked

        if (mc.isShowing()) {
            c.camposMODC(Tabla_c, mc.ID(), mc.nom(), mc.app(), mc.apm(), mc.dir(), mc.cor());
        }

    }//GEN-LAST:event_Tabla_cMouseClicked

    private void jbtnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiltroActionPerformed

        String cam = jtfCampo.getText();
        if (jcbxTipoFiltro.getSelectedItem().equals("Rut")) {
            c.filtrarCliente(Tabla_c, f.formatoRutfiltro(cam), jcbxTipoFiltro);
        } else {
            c.filtrarCliente(Tabla_c, cam, jcbxTipoFiltro);
        }


    }//GEN-LAST:event_jbtnFiltroActionPerformed

    private void jtfCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_c;
    private javax.swing.JButton btxActualizar_Cliente;
    private javax.swing.JButton btxEliminar_Cliente;
    private javax.swing.JButton btxModificar_Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtAgregar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JButton jbtnFiltro;
    private javax.swing.JComboBox<String> jcbxCiudad;
    private javax.swing.JComboBox<String> jcbxComuna;
    private javax.swing.JComboBox<String> jcbxRegion;
    private javax.swing.JComboBox<String> jcbxTipoFiltro;
    private javax.swing.JTextField jtfApm_c;
    private javax.swing.JTextField jtfApp_c;
    private javax.swing.JTextField jtfCampo;
    private javax.swing.JTextField jtfCorreo_c;
    private javax.swing.JTextField jtfDireccion_c;
    private javax.swing.JTextField jtfNombre_c;
    private javax.swing.JTextField jtfRut2_c;
    private javax.swing.JTextField jtfRut_c;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
